kind: Job 
apiVersion: batch/v1 
metadata:
  name: os-job
spec:
  template:
    spec:
      containers:
        - name: os-container
          image: centos:7
          command: ["bash"]
          args:
            - "-c"
            - "echo HELLO ; sleep 60 ; echo WORLD"
      restartPolicy: Never